# Generated by Django 5.2.7 on 2025-11-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_register_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('qualif', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rights', models.CharField(default='pharmacist', max_length=100)),
            ],
        ),
    ]
