# Generated by Django 5.2.7 on 2025-11-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_category_alter_register_phone_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
