# Generated by Django 5.2.7 on 2025-11-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_medicine_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='rx_required',
            field=models.BooleanField(default=False),
        ),
    ]
