# Generated by Django 5.2.7 on 2025-11-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_medicine_rx_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
