# Generated by Django 5.2.7 on 2025-11-24 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_medicine_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_medicines', to='myapp.pharmacist'),
        ),
    ]
