# Generated by Django 5.2.7 on 2025-11-24 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_medicine_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
    ]
