# Generated by Django 5.2.7 on 2025-11-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_prescription_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_available', models.BooleanField(default=True)),
                ('current_location', models.CharField(default='Headquarters', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('rights', models.CharField(default='delivery', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
