# Generated by Django 5.2.7 on 2025-11-28 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_deliveryagent_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.pharmacy'),
        ),
    ]
