# Generated by Django 5.2.7 on 2025-11-28 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_pharmacist_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='assigned_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.pharmacy'),
        ),
    ]
