# Generated by Django 5.2.7 on 2025-11-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_prescription_assigned_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='service_pincodes',
            field=models.TextField(default='', help_text='Enter pincodes separated by comma'),
        ),
    ]
