# Generated by Django 5.2.7 on 2025-11-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_prescription_service_pincodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='service_pincodes',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='service_pincodes',
            field=models.TextField(default='', help_text='Enter pincodes separated by comma'),
        ),
    ]
