# Generated by Django 5.2.7 on 2025-11-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_pharmacy_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
