# Generated by Django 5.2.7 on 2025-11-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_prescription_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='user_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
