# Generated by Django 5.2.7 on 2025-11-30 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_prescription_user_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='order_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='payment_mode',
            field=models.CharField(default='COD', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_prescriptions', to='myapp.pharmacist'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacist_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
