# Generated by Django 5.2.7 on 2025-12-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_order_order_group_id_order_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='handled_by',
        ),
        migrations.AddField(
            model_name='medicine',
            name='added_by_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_medicines', to='myapp.pharmacy'),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='rights',
            field=models.CharField(default='pharmacy', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='handled_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='locked_by_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_prescriptions', to='myapp.pharmacy'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Pharmacist',
        ),
    ]
