# Generated by Django 5.2.7 on 2025-12-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_prescription_locked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='order_group_id',
        ),
    ]
