# Generated by Django 5.2.7 on 2025-12-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_orderhistory_order_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='payment_mode',
        ),
    ]
