# Generated by Django 5.2.7 on 2025-12-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_orderhistory_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
