# Generated by Django 5.2.7 on 2025-12-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_register_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='zipcode',
            new_name='zip',
        ),
    ]
